dist: trusty
sudo: false
language: python
python:
    - "2.7"

notifications:
    email: false

cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U cpplint platformio

env:
    - PROJECT=Arduino/Navigation
    - PROJECT=Arduino/Propulsion
    - PROJECT=Arduino/Wireless_Basic
    - PROJECT=Arduino/Wireless_Boat
    - PROJECT=Arduino/Wireless_Shore

script:
    - cd $PROJECT
    - platformio run
    - cpplint --quiet --recursive .
