dist: trusty
sudo: false
language: python
python:
    - "2.7"

notifications:
    email: false

cache:
    directories:
        - "~/.platformio"

env:
    - PROJECT=Arduino/Propulsion

script:
    - cd $PROJECT
    - platformio run
    - cpplint --quiet --recursive .
